// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1654134354);
user_pref("app.update.lastUpdateTime.background-update-timer", 1654134594);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1654134474);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1654134234);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1654134714);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("browser.preferences.animateFadeIn", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20220517232952");
user_pref("extensions.lastAppVersion", "6.0.8");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.dataDir", "/home/bryan/Zotero");
user_pref("extensions.zotero.export.lastTranslator", "f895aa0d-f28e-47fe-b247-2ea77c6ed583");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportNotes\":false,\"exportFileData\":false,\"useJournalAbbreviation\":false,\"keepUpdated\":false,\"includeAnnotations\":false}");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastViewedFolder", "C42");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"false\",\"width\":\"240\"},\"zotero-collections-pane\":{},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 5);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"C80\",\"sessionID\":\"qcM1bjDc\"},{\"id\":\"C36\",\"sessionID\":\"A1ze5LuK\"},{\"id\":\"C29\",\"sessionID\":\"aoNOTxin\"},{\"id\":\"C42\",\"sessionID\":\"FPjwsUpX\"},{\"id\":\"C58\",\"sessionID\":\"5TH3xxdG\"},{\"id\":\"C34\",\"sessionID\":\"BVr6hp1u\"}]");
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"P1\":false}");
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1653407073);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "auth.lower + shorttitle(3,3) + year");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.useDataDir", true);
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1654050426);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1654050426);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1653422043);
